import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET() {
  // 1. Try Supabase index_live_cache table first
  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
    if (supabaseUrl && supabaseKey) {
      const sb = createClient(supabaseUrl, supabaseKey);
      const { data } = await sb
        .from('index_live_cache')
        .select('close_price, change_abs, change_pct, updated_at, source')
        .eq('symbol', 'SHARIAH')
        .eq('exchange', 'EGX')
        .single();

      if (data && data.close_price) {
        const updatedAt = new Date(data.updated_at);
        const ageMs = Date.now() - updatedAt.getTime();
        const stale = ageMs > 5 * 60 * 1000;

        return NextResponse.json(
          {
            value: data.close_price,
            change: data.change_pct,
            changeAbs: data.change_abs,
            source: data.source || 'tvdatafeed',
            updated_at: data.updated_at,
            stale,
            age_seconds: Math.round(ageMs / 1000)
          },
          { headers: { 'Cache-Control': 'no-store, max-age=0' } }
        );
      }
    }
  } catch {
    /* silent fallback */
  }

  // 2. Try Local JSON Cache generated by shariah_live_fetcher.py
  try {
    const cachePath = path.join(process.cwd(), '..', 'data', 'shariah_live_cache.json');
    if (fs.existsSync(cachePath)) {
      const raw = fs.readFileSync(cachePath, 'utf-8');
      const cacheData = JSON.parse(raw);
      if (cacheData && cacheData.close_price) {
        const updatedAt = new Date(cacheData.updated_at);
        const ageMs = Date.now() - updatedAt.getTime();
        return NextResponse.json(
          {
            value: cacheData.close_price,
            change: cacheData.change_pct,
            changeAbs: cacheData.change_abs,
            source: 'tvdatafeed',
            updated_at: cacheData.updated_at,
            stale: ageMs > 5 * 60 * 1000,
            age_seconds: Math.round(ageMs / 1000)
          },
          { headers: { 'Cache-Control': 'no-store, max-age=0' } }
        );
      }
    }
  } catch {
    /* silent fallback */
  }

  // 3. Fallback to Mubasher Scraping if no live feed cache exists
  try {
    const res = await fetch('https://www.mubasher.info/markets/EGX/indices/SHARIAH', {
      headers: { 'User-Agent': 'Mozilla/5.0' },
      cache: 'no-store',
      signal: AbortSignal.timeout(5000)
    });
    if (res.ok) {
      const html = await res.text();
      const priceMatch = html.match(/class="market-summary__last-price[^"]*">\s*([\d,.]+)/);
      const changeMatch = html.match(/class="market-summary__change-percentage[^"]*">\s*([-\d.%+]+)/);

      if (priceMatch && changeMatch) {
        const val = parseFloat(priceMatch[1].replace(/,/g, ''));
        const chg = parseFloat(changeMatch[1].replace(/%/g, ''));
        if (!isNaN(val) && !isNaN(chg)) {
          const p = parseFloat(val.toFixed(2));
          const c = parseFloat(chg.toFixed(2));
          return NextResponse.json(
            {
              value: p,
              change: c,
              changeAbs: parseFloat(((p * c) / 100).toFixed(2)),
              source: 'mubasher',
              stale: false
            },
            { headers: { 'Cache-Control': 'no-store, max-age=0' } }
          );
        }
      }
    }
  } catch {
    /* silent fallback */
  }

  return NextResponse.json(
    { error: 'No data', source: 'unavailable' },
    { status: 503, headers: { 'Cache-Control': 'no-store, max-age=0' } }
  );
}
